name: Build Mac App

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Publish self-contained app
        run: dotnet publish Program.cs -c Release -r osx-arm64 --self-contained true

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: DiscordStatus-macOS
          path: bin/Release/net8.0/osx-arm64/publish/
